export const projects = [
  {
    title: 'BookMyTheatre',
    slug: 'book-my-theatre',
    tagline: 'A real-time movie ticket booking platform supporting concurrent seat reservations.',
    overview:
      'BookMyTheatre is a full-stack movie ticket booking application built to handle concurrent seat selections and reservations in real-time. By utilizing Socket.IO for live updates and Redis for distributed locking, it guarantees a seamless booking experience without double-booking.',
    features: [
      'Real-time seat reservation & status updates via Socket.IO',
      'Distributed seat locking mechanism using Redis to prevent double booking',
      'Redis caching to optimize API response times and reduce database load by 40%',
      'Email OTP authentication and automated PDF/email ticket confirmations',
      'Containerized services using Docker and Docker Compose',
      'CI/CD deployment pipeline with GitHub Actions',
    ],
    techStack: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Redis', 'Socket.IO', 'Docker', 'GitHub Actions'],
    challenges: [
      'Preventing race conditions when multiple users try booking the same seat simultaneously.',
      'Synchronizing real-time seat states across active WebSocket connections.',
    ],
    learnings: [
      'Deepened expertise in distributed locking concepts and state synchronization.',
      'Learned how to set up robust Docker environments and CI/CD pipelines.',
    ],
    feedback: true,
    links: {
      live: 'https://book-my-theatre-tau.vercel.app',
      github: 'https://github.com/aashish733/BookMyTheatre',
    },
    thumbnail: '/projects picture/bmt/Screenshot 2026-06-15 231829.jpg',
    images: [
      '/projects picture/bmt/Screenshot 2026-06-15 231829.jpg',
      '/projects picture/bmt/theatre options.jpg',
      '/projects picture/bmt/selecting seats.jpg',
      '/projects picture/bmt/review booking.jpg',
      '/projects picture/bmt/otp verification.jpg',
      '/projects picture/bmt/booking confirm.jpg',
      '/projects picture/bmt/booking history.jpg',
    ],
  },
  {
    title: 'GoKart Hyperlocal Commerce Platform',
    slug: 'gokart',
    tagline: 'A hyperlocal commerce platform with asynchronous order pipelines and live tracking.',
    overview:
      'GoKart is a modern, hyperlocal e-commerce platform designed to bridge local merchants, customers, and delivery agents. It uses RabbitMQ to process orders asynchronously, improving reliability and decoupling microservices, while Leaflet provides real-time location mapping.',
    features: [
      'Asynchronous order processing pipeline decoupled using RabbitMQ message queues',
      'Modular REST APIs for catalog, inventory, order, cart, and user management',
      'Role-based access control (RBAC) for customers, vendors, and delivery agents',
      'Interactive Leaflet-based live delivery tracking',
      'Dockerized environment deployed on AWS EC2 infrastructure',
    ],
    techStack: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'RabbitMQ', 'Leaflet', 'Docker', 'AWS EC2'],
    challenges: [
      'Managing inventory consistency across multiple local vendors during peak order periods.',
      'Decoupling microservices reliably using RabbitMQ while handling message retries and DLQs.',
    ],
    learnings: [
      'Gained practical experience in message broker integration and microservice communication.',
      'Acquired skills in deploying containers on AWS EC2 and setting up reverse proxies with Nginx.',
    ],
    feedback: true,
    links: {
      live: 'https://gokart-hyperlocal-commerce-platform.vercel.app',
      github: 'https://github.com/aashish733/GoKart',
    },
    thumbnail: '/projects picture/gokart/home.jpg',
    images: [
      '/projects picture/gokart/home.jpg',
      '/projects picture/gokart/login page.jpg',
      '/projects picture/gokart/cartpage.jpg',
      '/projects picture/gokart/3dashboard.jpg',
      '/projects picture/gokart/live location.jpg',
      '/projects picture/gokart/delivered.jpg',
    ],
  },
  {
    title: 'Social Media Platform',
    slug: 'social-media-platform',
    tagline: 'A scalable MERN social media app with personalized feeds and real-time chatting.',
    overview:
      'This scalable social media platform enables users to share posts, like, comment, follow other profiles, and chat in real-time. By leveraging MongoDB Aggregation Pipelines and Redis caching, feed generation is optimized to run with high speed and low latency.',
    features: [
      'Real-time direct messaging and notifications using Socket.IO',
      'Highly optimized feed and recommendation system using MongoDB Aggregation Pipelines',
      'API rate limiting and Redis caching to protect server integrity and reduce query times by 35%',
      'Modular JWT-secured REST APIs following the MVC pattern',
      'Cloudinary integration for rich media uploads (posts, profile pictures)',
    ],
    techStack: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Redis', 'Socket.IO', 'Cloudinary', 'Tailwind CSS'],
    challenges: [
      'Aggregating personalized feed content efficiently across followers, likes, and comments.',
      'Implementing reliable, real-time messaging with online status indicators.',
    ],
    learnings: [
      'Mastered complex MongoDB aggregations and indexing techniques.',
      'Learned how to set up rate limiting and caching to prevent server overload.',
    ],
    feedback: true,
    links: {
      live: 'https://mern-social-media-project.vercel.app',
      github: 'https://github.com/aashish733/Social-Media-Platform',
    },
    thumbnail: '/projects picture/socialmedia/homepage.jpg',
    images: [
      '/projects picture/socialmedia/homepage.jpg',
      '/projects picture/socialmedia/loginpage.jpg',
      '/projects picture/socialmedia/profilepage.jpg',
      '/projects picture/socialmedia/chatiiing.jpg',
    ],
  },
  {
    title: 'FinSight',
    slug: 'finsight',
    tagline: 'An intuitive personal finance and transaction tracker with visual insights.',
    overview:
      'FinSight is a personal finance dashboard that allows users to record, categorize, and analyze their expenses and income. Through rich interactive charts and monthly reports, it helps users budget better and gain control over their financial health.',
    features: [
      'Intuitive dashboard showing real-time balance, income, and expense breakdowns',
      'Easy transaction creation with custom category, date, and description fields',
      'Dynamic monthly reports with visual data breakdowns using interactive charts',
      'Searchable and filterable transaction history logs',
      'Secure user registration and login system',
    ],
    techStack: ['React.js', 'Next.js', 'Node.js', 'Express.js', 'MongoDB', 'Tailwind CSS', 'Recharts'],
    challenges: [
      'Creating an intuitive and simple transaction form while ensuring robust database validations.',
      'Aggregating transactional data by month/category on the backend to render chart metrics smoothly.',
    ],
    learnings: [
      'Improved dynamic data rendering capabilities using charting libraries.',
      'Enhanced schema design practices for transactional ledger records.',
    ],
    feedback: true,
    links: {
      live: 'https://fin-sight-ai-omega-two.vercel.app',
      github: 'https://github.com/aashish733/FinSight',
    },
    thumbnail: '/projects picture/finsight/homepage.jpg',
    images: [
      '/projects picture/finsight/homepage.jpg',
      '/projects picture/finsight/Loginpage.jpg',
      '/projects picture/finsight/dashboard-homepage.jpg',
      '/projects picture/finsight/adding-transaction.jpg',
      '/projects picture/finsight/all-transactions.jpg',
      '/projects picture/finsight/monthly report.jpg',
    ],
  },
  {
    title: 'NextJob',
    slug: 'nextjob',
    tagline: 'A modern job search and recruitment board for job seekers and hiring managers.',
    overview:
      'NextJob is a comprehensive recruitment portal connecting talented candidates with top recruiters. It features dedicated dashboards for applicants to search and apply, and for recruiters to post jobs, track applications, and preview candidate profiles.',
    features: [
      'Dual-dashboard interface tailored for both recruiters and job seekers',
      'Comprehensive job search filters based on category, location, and job type',
      'Detailed job preview page showing responsibilities, requirements, and benefits',
      'Recruiter dashboard to create new listings, manage postings, and view applicant details',
      'Dynamic user profile page showcasing skills, education, and resume downloads',
    ],
    techStack: ['React.js', 'Next.js', 'Node.js', 'Express.js', 'MongoDB', 'Tailwind CSS'],
    challenges: [
      'Designing a clean, user-friendly recruiter portal to manage complex applicant pipelines.',
      'Ensuring seamless transitions between job search, filter options, and application forms.',
    ],
    learnings: [
      'Deepened understanding of role-based routing and page authorization in Next.js.',
      'Gained experience in structuring database relations between users, jobs, and applications.',
    ],
    feedback: true,
    links: {
      live: 'https://next-job-mauve.vercel.app',
      github: 'https://github.com/aashish733/NextJob',
    },
    thumbnail: '/projects picture/nextjob/homepage.jpg',
    images: [
      '/projects picture/nextjob/homepage.jpg',
      '/projects picture/nextjob/job page.jpg',
      '/projects picture/nextjob/job preview.jpg',
      '/projects picture/nextjob/job profile page.jpg',
      '/projects picture/nextjob/profile page.jpg',
      '/projects picture/nextjob/recruiter page.jpg',
    ],
  },
  {
    title: 'ReShop | PERN E-Commerce Platform',
    slug: 'reshop',
    tagline: 'A feature-rich e-commerce store with an integrated admin management panel.',
    overview:
      'ReShop is a high-performance e-commerce store featuring a full shopping cycle: product browsing, detailed views, a shopping cart, secure checkout, and order tracking. It includes a comprehensive admin dashboard to manage inventory, update orders, and analyze sales.',
    features: [
      'Clean and responsive product catalog with search, categorization, and details',
      'Interactive shopping cart and checkout pipeline with secure payment mockups',
      'Detailed order tracking and history logs for users',
      'Full Admin Dashboard for product listings, inventory controls, and order fulfillment',
      'Robust state management for smooth frontend updates and cart updates',
    ],
    techStack: ['React.js', 'PostgreSQL', 'Express.js', 'Node.js', 'Redux', 'Tailwind CSS'],
    challenges: [
      'Keeping local cart state in sync with database records and session persistence.',
      'Building a complete, secure admin interface to manage critical product and order state.',
    ],
    learnings: [
      'Strengthened skills in building complex CRUD operations and handling state changes using Redux.',
      'Learned how to design clean database models for multi-item checkout orders.',
    ],
    feedback: true,
    links: {
      live: 'https://pern-ai-eccomerce-webapp.netlify.app',
      github: 'https://github.com/aashish733/ReShop',
    },
    thumbnail: '/projects picture/reshop/homepage.jpg',
    images: [
      '/projects picture/reshop/homepage.jpg',
      '/projects picture/reshop/loginpage.jpg',
      '/projects picture/reshop/product page.jpg',
      '/projects picture/reshop/checkout page.jpg',
      '/projects picture/reshop/order page.jpg',
      '/projects picture/reshop/admin dashboard.jpg',
      '/projects picture/reshop/admin order page.jpg',
    ],
  },
];
